"use client";

import { nanoid }                    from "nanoid";
import { FaBed, FaHeadphones, FaTv } from "react-icons/fa";
import { GiSofa }                    from "react-icons/gi";
import { IoTabletPortrait }          from "react-icons/io5";
import {
  MdInventory,
  MdBuild,
  MdPhoneIphone,
  MdLaptop,
  MdKitchen,
  MdHome,
  MdChair,
  MdLightbulbCircle,
  MdOutlineDoorSliding,
} from "react-icons/md";

import { Product } from "./Columns";

export const products: Product[] = [
  {
    id: nanoid(),
    name: "Destornillador",
    supplier: "ToolSupplier Inc.",
    sku: "SD123",
    category: "Otros",
    status: "Borrador",
    quantityInStock: 50,
    price: 51960,
    icon: <MdBuild />,
    createdAt: new Date("2023-01-15"),
  },
  {
    id: nanoid(),
    name: "Martillo",
    supplier: "ToolSupplier Inc.",
    sku: "HM456",
    category: "Otros",
    status: "Publicado",
    quantityInStock: 30,
    price: 62000,
    icon: <MdInventory />,
    createdAt: new Date("2023-02-10"),
  },
  {
    id: nanoid(),
    name: "Teléfono Inteligente",
    supplier: "TechWorld",
    sku: "SP789",
    category: "Electronica",
    status: "Publicado",
    quantityInStock: 100,
    price: 1999960,
    icon: <MdPhoneIphone />,
    createdAt: new Date("2023-03-05"),
  },
  {
    id: nanoid(),
    name: "Computadora Portátil",
    supplier: "TechWorld",
    sku: "LT101",
    category: "Electronica",
    status: "Inactivo",
    quantityInStock: 25,
    price: 3599960,
    icon: <MdLaptop />,
    createdAt: new Date("2023-04-20"),
  },
  {
    id: nanoid(),
    name: "Horno Microondas",
    supplier: "HomeGoods Co.",
    sku: "MO202",
    category: "Muebles",
    status: "Borrador",
    quantityInStock: 15,
    price: 480000,
    icon: <MdKitchen />,
    createdAt: new Date("2023-05-18"),
  },
  {
    id: nanoid(),
    name: "Lavadora",
    supplier: "HomeGoods Co.",
    sku: "WM303",
    category: "Electrodomesticos",
    status: "Publicado",
    quantityInStock: 10,
    price: 1800000,
    icon: <MdHome />,
    createdAt: new Date("2023-06-22"),
  },
  {
    id: nanoid(),
    name: "Refrigerador",
    supplier: "HomeGoods Co.",
    sku: "RF404",
    category: "Electrodomesticos",
    status: "Inactivo",
    quantityInStock: 8,
    price: 3199960,
    icon: <MdKitchen />,
    createdAt: new Date("2023-07-10"),
  },
  {
    id: nanoid(),
    name: "Tableta",
    supplier: "TechWorld",
    sku: "TB505",
    category: "Electronica",
    status: "Borrador",
    quantityInStock: 60,
    price: 799960,
    icon: <MdLaptop />,
    createdAt: new Date("2023-08-15"),
  },
  {
    id: nanoid(),
    name: "Audífonos",
    supplier: "AudioTech",
    sku: "HP601",
    category: "Electronica",
    status: "Publicado",
    quantityInStock: 40,
    price: 319960,
    icon: <FaHeadphones />,
    createdAt: new Date("2023-09-01"),
  },
  {
    id: nanoid(),
    name: "Silla de Oficina",
    supplier: "FurnitureGalore",
    sku: "OC702",
    category: "Muebles",
    status: "Inactivo",
    quantityInStock: 20,
    price: 599960,
    icon: <MdChair />,
    createdAt: new Date("2023-10-12"),
  },
  {
    id: nanoid(),
    name: "Lámpara de Escritorio",
    supplier: "HomeGoods Co.",
    sku: "DL803",
    category: "Electronica",
    status: "Borrador",
    quantityInStock: 30,
    price: 139960,
    icon: <MdLightbulbCircle />,
    createdAt: new Date("2023-11-05"),
  },
  {
    id: nanoid(),
    name: "Mouse para Juegos",
    supplier: "TechWorld",
    sku: "GM904",
    category: "Electronica",
    status: "Publicado",
    quantityInStock: 55,
    price: 239960,
    icon: <MdHome />,
    createdAt: new Date("2023-12-01"),
  },
  {
    id: nanoid(),
    name: "Hervidor Eléctrico",
    supplier: "HomeGoods Co.",
    sku: "EK105",
    category: "Electrodomesticos",
    status: "Borrador",
    quantityInStock: 25,
    price: 159960,
    icon: <MdKitchen />,
    createdAt: new Date("2024-01-08"),
  },
  {
    id: nanoid(),
    name: "Parrilla Exterior",
    supplier: "HomeDepot",
    sku: "OG206",
    category: "Muebles",
    status: "Publicado",
    quantityInStock: 15,
    price: 999960,
    icon: <MdOutlineDoorSliding />,
    createdAt: new Date("2024-02-14"),
  },
  {
    id: nanoid(),
    name: "Taladro Inalámbrico",
    supplier: "ToolSupplier Inc.",
    sku: "CD307",
    category: "Otros",
    status: "Inactivo",
    quantityInStock: 35,
    price: 399960,
    icon: <MdBuild />,
    createdAt: new Date("2024-03-22"),
  },
  {
    id: nanoid(),
    name: "Televisor Inteligente",
    supplier: "TechWorld",
    sku: "ST408",
    category: "Electronica",
    status: "Borrador",
    quantityInStock: 22,
    price: 2399960,
    icon: <FaTv />,
    createdAt: new Date("2024-04-30"),
  },
  {
    id: nanoid(),
    name: "Mesa de Comedor",
    supplier: "FurnitureGalore",
    sku: "DT509",
    category: "Muebles",
    status: "Publicado",
    quantityInStock: 8,
    price: 1599960,
    icon: <IoTabletPortrait />,
    createdAt: new Date("2024-05-18"),
  },
  {
    id: nanoid(),
    name: "Auriculares Inalámbricos",
    supplier: "AudioTech",
    sku: "WE610",
    category: "Electronica",
    status: "Inactivo",
    quantityInStock: 45,
    price: 399960,
    icon: <FaHeadphones />,
    createdAt: new Date("2024-06-25"),
  },
  {
    id: nanoid(),
    name: "Decoración de Pared",
    supplier: "HomeGoods Co.",
    sku: "WD711",
    category: "Electrodomesticos",
    status: "Borrador",
    quantityInStock: 18,
    price: 119960,
    icon: <GiSofa />,
    createdAt: new Date("2024-07-03"),
  },
  {
    id: nanoid(),
    name: "Conjunto de Muebles para Exterior",
    supplier: "FurnitureGalore",
    sku: "OF812",
    category: "Muebles",
    status: "Publicado",
    quantityInStock: 12,
    price: 3199960,
    icon: <FaBed />,
    createdAt: new Date("2024-08-11"),
  },
];

